# Generated by Django 4.2.4 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_wallet_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='UserName', max_length=50),
        ),
    ]
