# Generated by Django 4.2.4 on 2023-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
