# Generated by Django 4.2.4 on 2023-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0006_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='prodents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='prodents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='prodents'),
        ),
    ]
