# Generated by Django 4.2.4 on 2023-11-22 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0007_alter_product_image2_alter_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
