# Generated by Django 4.2.4 on 2023-11-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0010_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
