# Generated by Django 4.2.4 on 2023-11-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0014_variant_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
