# Generated by Django 4.2.4 on 2023-11-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0014_variant_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_sid.brand'),
        ),
        migrations.AddField(
            model_name='variant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_sid.category'),
        ),
    ]
