# Generated by Django 4.2.4 on 2023-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sid', '0018_product_has_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_value',
            field=models.IntegerField(default=0),
        ),
    ]
