# Generated by Django 4.2.4 on 2023-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.CharField(max_length=10),
        ),
    ]
