# Generated by Django 4.2.4 on 2023-11-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
