# Generated by Django 4.2.4 on 2023-12-08 06:34

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_return_requested_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
